name: seele
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch==2.5.1
  - torchvision
  - pytorch-cuda=12.4
  - pip:
      - gradio==3.41.1
      - Pillow==9.4.0
      - tqdm==4.66.1
      - numpy==1.24.4
      - hydra-core>=1.3.2
      - iopath>=0.1.10
      - git+https://github.com/huggingface/diffusers

